[Update] Docs: enhance readme, add Community and Contributions section #14
janvi01/sql-editor pull request #16
Opened 2023-10-13 15:46 UTC by Freakyab

**Description**
- ... Added "Community and Contributions section" in readme file.
- ...Added contributors to the project in this section.

**Related issue(s)**
Resolves #14

2023-10-14 06:08 UTC, janvi01 requested changes

2023-10-14 06:08 UTC, janvi01 commented on README.md
> +# [Community](https://github.com/Freakyab/sql-editor/blob/main/CONTRIBUTING.md?plain=1) and [Contributions](https://github.com/Freakyab/sql-editor/blob/main/CONTRIBUTING.md?plain=1)
no need to add links in the heading, kindly remove
```suggestion
## Community and Contributions
```

2023-10-14 06:08 UTC, janvi01 commented on README.md
> +
You have pasted the content of CONTRIBUTING.md here, Please look at the screenshot example given in the issue. We don't want to add contribution guidelines in the readme, just want to reference the contributing.md file.

2023-10-14 06:08 UTC, janvi01 commented on README.md
> +### Contributors
```suggestion
### Thanks to these wonderful Contributors 🌻
```

2023-10-14 06:09 UTC, janvi01 commented
@Freakyab Thanks for the PR. Kindly make the required changes.

> Note: while creating a PR, always create a new branch. Keep this in mind for the next time. Follow the best [open-source practices](https://contributing.md/how-to-contribute-to-open-source/).

2023-10-14 18:30 UTC, Freakyab commented
please review the changes

2023-10-15 05:43 UTC, janvi01 approved these changes
LGTM 🚀

2023-10-15 05:44 UTC, merged