Fix: Mobile responsiveness for Query Output header
janvi01/sql-editor pull request #17
Opened 2023-10-14 09:53 UTC by 227001

I apologize for changing the size of the 'Query took' box. That's why I've created this PR to revert the 'Query took' box to its original size.
![截图57](https://github.com/janvi01/sql-editor/assets/145539206/0de39843-c123-41ae-83d7-d823c6c59238)
![截图22](https://github.com/janvi01/sql-editor/assets/145539206/032c0424-621a-4e1c-a15d-6c7a92cb8988)

2023-10-20 12:29 UTC, janvi01 requested changes
Hey @227001 Thanks for the PR. The code and the implementation look good to me.

One thing here is we can optimize the code, you have implemented separate code for both mobile view and larger view by separate boxes and using `display` attr. This can be done easily using a single `stack` in chakra ui and just setting the direction of the stack as `column` for mobile view and `row` for large screen view.

I have requested the changes, kindly look at that and see where you could optimize. Implement the changes, then this PR would be ready to merge.

2023-10-20 12:29 UTC, janvi01 commented on src/components/Output/OutputDisplay.js
>  };
```suggestion
    return (
    <>
      {results.length > 0 ? (
        <>
          <Stack
            direction={["column", "row"]}
            w={"100%"}
            px={4}
            justifyContent={"space-between"}
          >
            <Heading textAlign="center" fontSize={"3xl"}>
              Query Output
            </Heading>
            <Spacer />
            <HStack justify={"center"}>
              <Button colorScheme="blue" cursor="initial" size={"xs"}>
                Query took: {queryTime}
              </Button>
              <CsvDownload data={results} filename={`${filename}.csv`}>
                <Button
                  leftIcon={<BsFillFileEarmarkArrowDownFill />}
                  colorScheme="blue"
                  fontSize={"xl"}
                >
                  Export CSV
                </Button>
              </CsvDownload>
            </HStack>
          </Stack>
          <OutputTable data={results} />
        </>
      ) : (
        <VStack justifyContent="center" p={4}>
          <Image
            src={girlWithLaptopImage}
            alt="Girl With Laptop"
            maxH="300px"
          />
          <Heading as="h1" fontSize="xl" mt={4}>
            Nothing to show at the moment
          </Heading>
          <Text>Run a query first to see resulting tablet</Text>
        </VStack>
      )}
    </>
  );
};
```

2023-10-23 06:19 UTC, janvi01 commented
@227001 any updates?

2023-10-25 08:25 UTC, 227001 commented
updated

2023-10-26 05:45 UTC, janvi01 approved these changes
LGTM @227001

2023-10-26 05:47 UTC, merged