Adding Footer
janvi01/sql-editor pull request #23
Opened 2023-10-18 13:00 UTC by Ferdinand-Ogama

**Description**
-	I can’t find the documentation. Please direct me.
-	I have added the footer section on the website. The challenge I ran into was removing the horizontal strip between the footer and the bottom of the screen. I tried changing the screen view height, but it couldn’t work. 
-	This is what it looks like: 

![Untitled](https://github.com/janvi01/sql-editor/assets/111184823/3c29245f-67c5-403f-8836-a2c8be87c0a8)

2023-10-22 06:59 UTC, janvi01 requested changes
LGTM 🚀 Kindly make the required changes @Ferdinand-Ogama Thanks!

2023-10-22 06:59 UTC, janvi01 commented on src/components/Footer/Footer.js
> +                SQL Online Editor - Copyright © {currentYear}
Highlight the `janvi01` link, in spite of `a` tag you can use `link` tag

```suggestion
                SQL Online Editor - Copyright © {currentYear} | Created by <a href="https://github.com/janvi01" target="_blank">janvi01</a>
```

2023-10-22 06:59 UTC, janvi01 commented on src/components/Footer/Footer.js
> +                </Link>
```suggestion
```

2023-10-22 06:59 UTC, janvi01 commented on src/pages/FrontLayout.js
> +      <Footer />
add the footer component in `App.js` not in `FrontLayout.js`

2023-10-22 23:59 UTC, Ferdinand-Ogama commented
Hello,  I have applied the changes.

2023-10-25 08:05 UTC, janvi01 approved these changes
LGTM @Ferdinand-Ogama I have made minor required changes, you can just go through what changes I have made in the recent commit. Also, use `prettier` to format code for this project from next time.

2023-10-25 08:05 UTC, merged